---
title: "Pełny proces analizy: Od danych do rankingu"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pełny proces analizy: Od danych do rankingu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# Wczytywanie 
library(SocialAddictionRankR)
data("social_media_data")

# Definicja struktury kryteriów
skladnia_modelu <- "
  Uzytkowanie =~ avg_daily_usage; 
  Dobrostan   =~ mental_health + sleep;   Negatywy    =~ addicted_score + conflicts
"

# Automatyczna transformacja do postaci rozmytej (TFN)
macierz_rozmyta <- przygotuj_dane_mcda(
  dane = social_media_data,
  skladnia = skladnia_modelu,
  kolumna_alternatyw = "most_used_platform"
)

# Podgląd przetworzonej macierzy
knitr::kable(head(macierz_rozmyta, 5))

# Podgląd struktury surowych danych
head(social_media_data)

# Definiowanie modelu i agregacja rozmyta
skladnia_modelu <- "
  Uzytkowanie =~ avg_daily_usage; 
  Dobrostan   =~ mental_health + sleep;   Negatywy    =~ addicted_score + conflicts
"

macierz_rozmyta <- przygotuj_dane_mcda(
  dane = social_media_data,
  skladnia = skladnia_modelu,
  kolumna_alternatyw = "most_used_platform"
)

# Podgląd przetworzonych danych
knitr::kable(head(macierz_rozmyta, 5), caption = "Zagregowana rozmyta macierz decyzyjna (fragment)")

# Wektory porównań (Kryteria: Uzytkowanie, Dobrostan, Negatywy)
# Dobrostan (poz. 2) uznano za najlepszy, Uzytkowanie (poz. 1) za najgorszy
nazwy <- c("Uzytkowanie", "Dobrostan", "Negatywy") 
bwm_best <- c(4, 1, 2)  
bwm_worst <- c(1, 4, 3) 

wagi_sm <- oblicz_wagi_bwm(
  nazwy_kryteriow = nazwy,
  najlepsze_do_innych = bwm_best,
  inne_do_najgorszego = bwm_worst
)

# Definicja typów kryteriów (min = koszt, max = zysk)
typy <- c("min", "max", "min")

# Uruchomienie zintegrowanego silnika obliczeniowego
meta_wynik <- rozmyty_meta_ranking(
  macierz_decyzyjna = macierz_rozmyta,
  typy_kryteriow = typy,
  bwm_najlepsze = bwm_best,
  bwm_najgorsze = bwm_worst
)
korelacje <- meta_wynik$korelacje

# Generowanie Mapy Strategicznej VIKOR 
plot(meta_wynik$detale_vikor) 

# Generowanie Mapy Efektywności TOPSIS 
plot(meta_wynik$detale_topsis)

# Generowanie sformatowanego raportu tabelarycznego w standardzie APA  
tabela_apa(meta_wynik)
